[build]
  publish = "dist"
  command = "echo 'Static files ready'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-render-app.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "https://your-render-app.onrender.com/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://your-render-app.onrender.com/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
