[build]
  publish = "dist"
  command = "python build_frontend.py"

# Build environment
[build.environment]
  PYTHON_VERSION = "3.9"

# API redirects - Update with your actual Render URL
[[redirects]]
  from = "/api/*"
  to = "https://your-render-app.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "https://your-render-app.onrender.com/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://your-render-app.onrender.com/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
